/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.consultorio_fuboca.view;

/**
 *
 * @author aluno.den
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnCadastrarMedico = new javax.swing.JMenuItem();
        btnAlterarMedico = new javax.swing.JMenuItem();
        btnListarMedicos = new javax.swing.JMenuItem();
        btnDeletarMedico = new javax.swing.JMenuItem();
        btnCadastrarPaciente = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        btnAlterarPaciente = new javax.swing.JMenuItem();
        btnListarPacientes = new javax.swing.JMenuItem();
        btnDeletarPaciente = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        btnCadastrarConsulta = new javax.swing.JMenuItem();
        btnAlterarConsulta = new javax.swing.JMenuItem();
        btnListarConsultas = new javax.swing.JMenuItem();
        btnDeletarConsulta = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consultório");

        Desktop.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenu1.setText("Medicos");

        btnCadastrarMedico.setText("Cadastrar");
        btnCadastrarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarMedicoActionPerformed(evt);
            }
        });
        jMenu1.add(btnCadastrarMedico);

        btnAlterarMedico.setText("Alterar");
        jMenu1.add(btnAlterarMedico);

        btnListarMedicos.setText("Listar");
        jMenu1.add(btnListarMedicos);

        btnDeletarMedico.setText("Deletar");
        btnDeletarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarMedicoActionPerformed(evt);
            }
        });
        jMenu1.add(btnDeletarMedico);

        jMenuBar1.add(jMenu1);

        btnCadastrarPaciente.setText("Pacientes");

        jMenuItem2.setText("Cadastrar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        btnCadastrarPaciente.add(jMenuItem2);

        btnAlterarPaciente.setText("Alterar");
        btnCadastrarPaciente.add(btnAlterarPaciente);

        btnListarPacientes.setText("Listar");
        btnCadastrarPaciente.add(btnListarPacientes);

        btnDeletarPaciente.setText("Deletar");
        btnCadastrarPaciente.add(btnDeletarPaciente);

        jMenuBar1.add(btnCadastrarPaciente);

        jMenu3.setText("Agendamentos de Consultas");

        btnCadastrarConsulta.setText("Cadastrar");
        btnCadastrarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarConsultaActionPerformed(evt);
            }
        });
        jMenu3.add(btnCadastrarConsulta);

        btnAlterarConsulta.setText("Alterar");
        jMenu3.add(btnAlterarConsulta);

        btnListarConsultas.setText("Listar");
        jMenu3.add(btnListarConsultas);

        btnDeletarConsulta.setText("Deletar");
        jMenu3.add(btnDeletarConsulta);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarMedicoActionPerformed
        // TODO add your handling code here:
        TelaCadastroMedico CadMedico = new TelaCadastroMedico();
        Desktop.add(CadMedico);
        CadMedico.setVisible(true);
        
    }//GEN-LAST:event_btnCadastrarMedicoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnCadastrarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarConsultaActionPerformed
        // TODO add your handling code here:
        TelaCadastroPaciente CadPaciente = new TelaCadastroPaciente();
        Desktop.add(CadPaciente);
        CadPaciente.setVisible(true);
    }//GEN-LAST:event_btnCadastrarConsultaActionPerformed

    private void btnDeletarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarMedicoActionPerformed
        // TODO add your handling code here:
        TelaDeletarMedico DelMedico = new TelaDeletarMedico();
        Desktop.add(DelMedico);
        DelMedico.setVisible(true);
    }//GEN-LAST:event_btnDeletarMedicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuItem btnAlterarConsulta;
    private javax.swing.JMenuItem btnAlterarMedico;
    private javax.swing.JMenuItem btnAlterarPaciente;
    private javax.swing.JMenuItem btnCadastrarConsulta;
    private javax.swing.JMenuItem btnCadastrarMedico;
    private javax.swing.JMenu btnCadastrarPaciente;
    private javax.swing.JMenuItem btnDeletarConsulta;
    private javax.swing.JMenuItem btnDeletarMedico;
    private javax.swing.JMenuItem btnDeletarPaciente;
    private javax.swing.JMenuItem btnListarConsultas;
    private javax.swing.JMenuItem btnListarMedicos;
    private javax.swing.JMenuItem btnListarPacientes;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
